version: '3'

services:
  radicale:
    image: tomsquest/docker-radicale:latest
    ports:
      - 127.0.0.1:5232:5232
    volumes:
      - ./config:/config:ro
      - data:/data
    env_file:
      - radicale.env
    networks:
      - radicale_frontend 

volumes:
  data:

networks:
  radicale_frontend:
     external: true

