version: "3"

services:
  mesa:
    build: .
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - DISPLAY=:0
      - DOCKER_NAME=mesa-devel
    volumes:
      - ~/.ssh:/home/jasuarez/.ssh:ro
      - ~/Projects/mesa:/home/jasuarez/Projects/mesa
      - /tmp/.X11-unix:/tmp/.X11-unix:Z
      - mesa:/opt

volumes:
  mesa:
