version: "3"

services:
  devel:
    build:
      context: .
      args:
        username: "jasuarez"
        useruid: 1000
        usergid: 1002
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - DISPLAY=:0
      - DOCKER_NAME=mesa
    volumes:
      - ~/.ssh:/home/jasuarez/.ssh:ro
      - ~/Projects/mesa:/home/jasuarez/Projects/mesa
      - /tmp/.X11-unix:/tmp/.X11-unix:Z
      - ccache:/opt/ccache
      - jhbuild:/opt/jhbuild

volumes:
  ccache:
  jhbuild:
